version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - pizzeria-net

  menu-service:
    build: ./menu-service
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - pizzeria-net

  client-service:
    build: ./client-service
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    networks:
      - pizzeria-net

  kitchen-service:
    build: ./kitchen-service
    ports:
      - "8083:8080"
    depends_on:
      - postgres
    networks:
      - pizzeria-net

  order-service:
    build: ./order-service
    ports:
      - "8084:8080"
    depends_on:
      - postgres
    networks:
      - pizzeria-net

volumes:
  pg_data:

networks:
  pizzeria-net:
